FROM swift:5.10.1-noble as builder

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get install -y \
    software-properties-common \
    libpq-dev \
    libpng-dev \
    libjpeg-dev \
    libjavascriptcoregtk-4.1-dev \
    libatomic1 \
    libtesseract-dev \
    libleptonica-dev
    
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /root/Spyglass
COPY ./.build/repositories ./.build/repositories
COPY ./.git ./.git
COPY ./Makefile ./Makefile
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift package resolve
RUN swift build --configuration release
RUN swift test -v

FROM swift:5.10.1-noble-slim

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get -q install -y \
    software-properties-common \
    libpq-dev \
    libpng-dev \
    libjpeg-dev \
    libjavascriptcoregtk-4.1-dev \
    libatomic1 \
    plzip \
    libtesseract5
    
RUN rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/Spyglass/.build/debug/Spyglass.build/Spyglass.swift.o .
