FROM fedora:38 as builder

RUN dnf install -y \
    git \
    unzip \
    swift-lang-5.7.3-2.fc38 \
    javascriptcoregtk4.1-devel \
    tesseract-devel \
    leptonica-devel \
    libatomic_ops

RUN ln -s /usr/libexec/swift/*/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so

WORKDIR /root/Spyglass
COPY ./.build/repositories ./.build/repositories
COPY ./.git ./.git
COPY ./Makefile ./Makefile
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift package resolve
RUN swift build --configuration release
RUN swift test -v

FROM alpine

COPY --from=builder /root/Spyglass/.build/debug/Spyglass.build/Spyglass.swift.o .
